### ISSUE TITLE
Missing technology option translations

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#220]
<img width="731" alt="image" src="https://github.com/user-attachments/assets/0de0be54-dddd-47c7-b4a4-2ae3481eec51">

For web frameworks, cloud platforms, development processes, productivity tools.

**Comment by pwim** [comment]
This is broken again...

**Comment by SachaG** [comment]
Sorry about that. The issue was that I modified how the API works so that it can fetch config YAMLs from multiple locations (e.g. the global devographics repo + the specific tokyodev repo) but I had forgotten to actually add the path to the devographics repo, so it was not finding the metadata for these items anymore.
