### ISSUE TITLE
% of bucket in salary breakdown doesn't always add up to 100%

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#95]
<img width="954" alt="Screenshot 2023-11-08 at 14 36 00" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/30756/07308608-d821-482e-ae66-b50ef53a9d66">

**Comment by pwim** [comment]
To be clear, this isn't just a display issue. "Overall" adds up to 120% (with no answer accounting for the extra 20%).

**Comment by SachaG** [comment]
The extra 20% for the Overall bar are the "no answer" bucket. I think it's probably an issue of correctly distinguishing between "people who didn't answer the Japanese Prefecture question" and "people who didn't answer the Salary question". There might be a mix-up at some point. 

Also note that after correcting a few other issues with the privacy cutoff the bars don't always add up to 100%:

<img width="947" alt="Screenshot 2023-11-09 at 15 14 11" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/bb3b6fa1-dedc-42d0-ac2e-829d8fe80a7f">

For example here the Kanagawa bars doesn't reach 100% because some of the segments represent less than 10 respondents, so they're hidden. I think I might be able to merge them into a single "insufficient data" bar but it'll take a bit of hacking around the dataviz library I'm using…

**Comment by SachaG** [comment]
Also did you find other bars that went over 100% or was it just the Overall bar?

**Comment by SachaG** [comment]
Right, after thinking about it in a way the current chart is correct. The "No Answer" in Overall means "respondents who didn't answer the Japanese Province question" why the "No Answer" in Tokyo are the subgroup of respondents to "Japanese Province" who didn't provide their salary. 

I think we can just drop the "no answer" bucket from the "overall" bar in this case since it's confusing to have two different reference points in the same chart.
