### ISSUE TITLE
How to handle non-linear percentile scales?

### ISSUE THREAD

**Issue by pwim** [tokyodev-inc/tokyodev-devographics#99]

**Comment by SachaG** [comment]
Oh it looks like there's a couple questions where I haven't defined the approximate averages we use for each range, so that's why they're not working yet.

**Comment by SachaG** [comment]
<img width="933" alt="Screenshot 2023-11-09 at 10 16 02" src="https://github.com/tokyodev-inc/tokyodev-devographics/assets/358832/75ea8041-c004-4df4-af71-7de9013ea84f">

It looks a little weird because our company size options (1 person, 2-9, 10-19, 20-99, 100-499, etc.) don't follow a linear scale. I can probably tweak the scale in D3 but I'm not sure yet how to do it in a way that's easy to systematize. I guess ideally the D3 scale should be generated from the options directly?

**Comment by pwim** [comment]
You're right that calculating the scale, and maybe using a logarithmic one in this case would be ideal. However, I don't think it is so important to show percentiles for company size. Could we just disable the chart in this case, so it doesn't throw an error?

**Comment by SachaG** [comment]
Oh it doesn't throw an error, it works but just looks different from the other percentile charts because of the scale issue.

**Comment by pwim** [comment]
I meant that without resolving the scale issue, maybe we should just remove the chart. But if you think it's okay as is, we could leave it.

**Comment by SachaG** [comment]
It's technically correct so I think we can leave it at least for now.
